### ISSUE TITLE
demo link broken

### ISSUE THREAD

**Issue by katapofatico** [victorjonsson/jquery-editable#9]
Hello :)
here:
https://github.com/victorjonsson/jquery-editable/blob/master/README.md
the text
"Live example can be viewed here"
 links to 
http://victorjonsson.se/168/jquery-editable/?from=github
and it says: 
Forbidden, You don't have permission to access /168/jquery-editable/ on this server.

**Comment by Jagarm** [comment]
The link is still broken, as I would like to know what this plugin can accomplish

**Comment by victorjonsson** [comment]
http://codepen.io/anon/pen/OMWJOY
